### ISSUE TITLE
How to Minimize the Size of Shellcode?

### ISSUE THREAD

**Issue by 10cks** [Cracked5pider/Stardust#5]
I tried to implement the shellcode on a single page, but it still came out to be 4128 bytes.
The source code is filled with a large number of zero bytes in order to get the page together.
So how do I reduce shellcode volume?

**Comment by xrombar** [comment]
Memory protections on Windows are on a per-page basis. Stardust adds padding between the actual code and the "global" section (which just stores the pointer to the heap) to ensure that the former is RX and the latter RW without any conflict.

Thus it's guaranteed that when using Stardust your shellcode will be atleast a page in size, since the code needs to be padded to page boundary for the protection trick. There is no way around this (apart from just finding another way than how Stardust does it).

**Comment by 10cks** [comment]
> our s

thanks, I understand.

**Comment by 10cks** [comment]
> Memory protections on Windows are on a per-page basis. Stardust adds padding between the actual code and the "global" section (which just stores the pointer to the heap) to ensure that the former is RX and the latter RW without any conflict.
> 
> Thus it's guaranteed that when using Stardust your shellcode will be atleast a page in size, since the code needs to be padded to page boundary for the protection trick. There is no way around this (apart from just finding another way than how Stardust does it).

thanks, I understand.
